caddyserver/certmagic

README.md

Minor documentation error. Seems like the rest of the doc is correct, but as I copy-pasta'd this, I was very sad that it didn't work first go.
> __Edit:__ I also read [don't push your pull requests](https://www.igvita.com/2011/12/19/dont-push-your-pull-requests/) far too late. I can retry if you'd prefer 😨

fix: first readme example does not use a string slice

---

README.md

The wording:
> Compared to other ACME client libraries for Go, only CertMagic supports the full suite of ACME features, and no other library will ever match CertMagic's maturity and reliability.
comes off aggressively boastful and packed with hubris. 
I've reworded the sentence to be a bit more down to earth.
> Compared to other ACME client libraries for Go, only CertMagic supports the full suite of ACME features, and no other library matches CertMagic's maturity and reliability.

Removes immodest language

---

filestorage.go
solvers.go
storage.go

Really simple change here.  Simply changing the `KeyBuilder.Safe()` function to be exported instead of internal to certmagic.  This allows other storage implementations to take advantage of the method without re-implementing the entire type.
Hope that's OK and makes sense!

exported KeyBuilder.Safe to use with external pkgs

---

config.go
user.go
user_test.go

This PR fixes mholt/caddy#2400
The initial problem can be reproduced by this test.
https://github.com/crvv/certmagic/commit/c48d69ec1aa2b9e6abee1b666dcf43c2899930b6
However, `getEmail` doesn't need to create the new user.
The new user will be created by `newACMEClient` and the new user will be saved to disk after registration in `newACMEClient`.
With this PR, `getEmail` just get an email and save that value to `Config`.

user: don't create new user in getEmail

---

.travis.yml
README.md
appveyor.yml
certmagic.go
client.go
config.go
config_test.go
crypto.go
go.mod
go.sum
handshake.go
httphandler.go
ocsp.go
solvers.go
user.go
user_test.go

Getting errors when trying to `go get ./...` in caddy
```
../../mholt/certmagic/client.go:98:29: cannot use &leUser (type *user) as type "github.com/go-acme/lego/registration".User in argument to lego.NewConfig:
*user does not implement "github.com/go-acme/lego/registration".User (wrong type for GetRegistration method)
have GetRegistration() *"github.com/xenolf/lego/registration".Resource
want GetRegistration() *"github.com/go-acme/lego/registration".Resource
../../mholt/certmagic/client.go:103:4: cannot use keyType (type "github.com/xenolf/lego/certcrypto".KeyType) as type "github.com/go-acme/lego/certcrypto".KeyType in field value
../../mholt/certmagic/client.go:128:72: cannot use "github.com/xenolf/lego/registration".RegisterOptions literal (type …
```

use go-acme/lego

---

certmagic.go

will also allow IE11 to use GCM ciphers (indirect fix for mholt/caddy#2496 )

Change default KeyType to EC256 (P256)

---

client.go
config.go

This PR adds a new Config option to allow the user to define custom `dns01.ChallengeOption` for their `dns01.Provider`. This gives optionally more control for the advanced users of certmagic.
When running DNS servers behind firewalls with address translation, it may prove difficult for the default validation functions of `lego` to successfully return. This is true even in cases where the validation should succeed. 
The reason for this is that some firewalls struggle with packets from LAN towards WAN IP that actually points back to the LAN. This is usually handled by [split-horizon DNS](https://en.wikipedia.org/wiki/Split-horizon_DNS), but in this use case it proves insufficient.
With this option, the user is able to add a custom DNS resolvers, modify the propagation check rules or change …

Add an Config option for custom ChallengeOptions

---

README.md

https://blog.golang.org/pkg.go.dev-2020
Go team launched new package documentation website, https://pkg.go.dev .
In the blog post, go team encourage to use https://pkg.go.dev .
So I changed godoc links into pkg.go.dev

Change godoc to pkg.go.dev in README.md

---

certmagic.go

Fix for https://github.com/caddyserver/certmagic/issues/64

Fix CertificateResource.NamesKeys() truncation

---

go.mod

Function handshake.DefaultCertificateSelector uses the field
`*tls.ClientHelloInfo.SupportsCertificate` which only supported in go 1.14

chore: update go version declared in go.mod

---

config.go
filestorage.go
storage.go

This allows callers to give up if they can't obtain a lock in a certain
timeframe and for resources to be cleaned up, avoiding potential
resource leaks.
Breaking change for any Storage implementations, sorry about that. (It's
why we're not 1.0 yet.) I'll reach out to known implementations; it's a
simple change.

Lock now takes a context and should honor cancellation

---

dnsutil.go

Sometimes incoming udp traffic on port 53 is blocked to prevent DDoS attacks. In those cases only TCP will work for DNS request as the UDP request will time out. And as a result the DNS challenge will fail, while the server is trying to verify if the challenge was propageted through the NS.
Now instead of returning immidently, if a timeout with UDP was received, the request will be tried again using TCP.

Minor improvement to DNS request handling

---

account.go

Handles `decodePrivateKey` error and returns after adding some context to it. See https://github.com/caddyserver/certmagic/blob/4fd8ae48ef87c9fd8917659cfb53aac98f48ecac/account.go#L56
Until now, error was silently ignored. It should be handled or explicitly ignored. Now, if we fail to decode user's private key, they will know.
Please, feel free to close this PR if you disagree.
Fixes #88.
`go test -race -v ./...`
`1.15` and `tip`.

account: handle decodePrivateKey() error in getAccount

---

dnsutil.go

Replaces an error to string coversion using `fmt.Sprintf` by calling `Error()` method on that error.
Code readability.
`go test -race -v ./...`
`1.15` and `tip`.

dnsutil: replace fmt.Sprintf() with err.Error() when formatting errors

---

account.go
account_test.go
acmeclient.go
acmemanager.go
certificates.go
certmagic.go
config.go
config_test.go
crypto.go
handshake.go
httphandler.go
httphandler_test.go
solvers.go

This change refactors Config.Issuer to be Config.Issuers, an array of
issuers. Each Issuer will be tried in turn until one succeeds. During
retries, each attempt will try each configured Issuer. When loading
certs from storage, CertMagic will look in each Issuer's storage
location for a qualifying asset. If multiple Issuers have one in storage
then the most-recently-issued cert will be selected.
This is a breaking change in that Config now accepts a slice of Issuers
rather than a single Issuer. The Revoker field is removed, as supporting
it is optional anyway. If the Issuer is also a Revoker, it can be used
implicitly to revoke certificates.
Also added a const for ZeroSSL's ACME endpoint.
Also, bug fixes for distributed solving of TLS-ALPN challenge:
The type assertion in handshake.go was …

Implement multiple issuer support

---

config.go

Closes: https://github.com/caddyserver/certmagic/issues/92
Does this match what you had in mind?
Do we also need to do some `Storage` cleanups?

Add Config.Unmanage

---

README.md

As reported in #113, the example code for implementing a DNS provider does not compile,
and in my opinion results in a cryptic message. (maybe everybody else figures it out? )
Nonetheless, I thought this fix would be a nice contribution to help others avoid having to try to figure out
that message.

fix dns solver example code to compile okay

---

dnsutil.go
dnsutil_test.go

Make configured resolvers important and do not allow any fallback or other ones being used.
This solves some issues when for example using a split-head DNS and certmagic falls back to using /etc/resolve.conf.
It forces the use of only the configured resolvers and nothing else.
__ Caddyfile__
```
resolvers ns1.loopia.se !important
resolvers ns1.loopia.se!important
```
__JSON__ 
```json
"resolvers": [
"ns1.loopia.se",
"!important"
]
```
alternatively
```json
"resolvers": [
"ns1.loopia.se!important"
]
```

Prioritize the configured resolvers

---

config.go

Commit 388f3ed introduced new log statements that were not guarded by the typical `if log != nil {...` pattern seen elsewhere in the codebase. This resulted in a segfault at runtime:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x81cbe7]
goroutine 1 [running]:
go.uber.org/zap.(*Logger).check(0x0, 0xff, 0xc0002f0d98, 0x11, 0xc00021ce80)
/Users/ryan/Projects/go/pkg/mod/go.uber.org/zap@v1.17.0/logger.go:265 +0x987
go.uber.org/zap.(*Logger).Debug(0x0, 0xc0002f0d98, 0x11, 0xc00021ce80, 0x1, 0x1)
/Users/ryan/Projects/go/pkg/mod/go.uber.org/zap@v1.17.0/logger.go:180 +0x45
github.com/caddyserver/certmagic.(*Config).obtainCert.func2(0xd8ad08, 0xc000034070, 0xd91650, 0x11d4b80) …
```

Add checks if log is nil

---

config.go

The `newWithCache` func inside `config.go` has duplicate check and assign statement for `cfg.OnDemand`.

duplicate OnDemand default value assign check

---

handshake.go

This fixes a small bug that happened when the `cfg.certCache.options.Capacity` is 0 (unlimited).
I noticed that certificates I did not `Manage` or manually `Unmanage`'d got loaded from storage. This was unexpected and I traced it down to this bug that causes `cacheAlmostFull` to always be true, if the capacity is set to 0.
In the meantime, this can be mitigated by setting the capacity to `math.MaxInt32`.

Fix cacheAlmostFull calculation

---

certificates.go
config.go
handshake.go
maintain.go
ocsp.go

Follow-up to 9245be5a2f16135b9de55567682f49a2d343e1f0
Now I remember why I didn't implement this at first. Kind of complicated... and nobody at the time really needed it, as far as I knew.

Fix force-renewing revoked on-demand certs

---

crypto.go

The order of storing the certificates was previously changed so that the private key would be stored first. For anyone who is creating storage hooks which push the certificate & key to a 3rd party service (like a CDN), the certificates are generally refused if uploaded before the private key.
Loading can trigger the same issue if (for any reason), the certificate & key have been deleted on the 3rd party service.
I'll admit that this use-case stretches what the storage system should be doing, but the change is trivial & just matches the storing side.

Fixed order of certificate loading so that private keys are loaded first

---

account.go
certificates.go
certificates_test.go
certmagic.go
config.go
crypto.go
crypto_test.go
handshake.go

This is useful if another entity is managing certificates and can provide its own certs dynamically during handshakes.
For example, Tailscale's client has a `GetCertificate()` function: https://pkg.go.dev/tailscale.com/client/tailscale#GetCertificate

Managers: Ability to call GetCertificate from external certificate sources

---

dnsutil.go
solvers.go

CNAME can be used to delegate answering the chanllenge to another DNS
zone, in order to reduce the exposure of the DNS credential [1]. The
solver already follows CNAME when checking propagation against the
authoritative source, it should follow CNAME when setting the TXT record
as well.
[1] https://letsencrypt.org/docs/challenge-types/#dns-01-challenge

Support OverrideDomain is DNS01Solver

---

maintain.go

Hello,
I got again the very uncommon crash I talked about on the forum: https://caddy.community/t/strange-invalid-memory-address-or-nil-pointer-dereference-with-custom-build/13867
And I'm happy to say I found the issue ! :) 
So, here is my PR to fix it, but feel free to do it in another way if you wish, as I have almost zero XP in golang.
The root cause, is updateOCSPStaples() inserting a zeroed cert into cache.
The full chain of events:
* a cert A is pushed to the `updated` queue in `updateOCSPStaples()`
* in parallel a new cert B is evicting this very same cert A from the full cache, to make some room.
* `updateOCSPStaples()` while iterating `updated` queue is trying to get cert A from cache, but got a zeroed struct, update some fields, and insert this zeroed cert to cache.
* finally a …

Fix crash because of a zero value cert in cache

---

config.go

The `cert_*` events were only providing the domain. This was pretty limited, because not much can be done with it without also knowing the issuer, since that affects where the cert is stored.
Providing both the `issuerKey` and `certKey` makes it possible for the event listener to call `StorageKeys.SiteCert(issuerKey, certKey)` to get the actual location of the cert (and similarly the private key). Particularly useful in situations where the user wants to copy the cert/key to some location for another app to use the cert that is being managed.
A similar change could probably also be done for `cached_managed_cert` and `cached_unmanaged_cert` events to provide more detail, because `cert.Names` string slice doesn't seem that useful, can't do much with that alone. But I'm not sure I understand …

Provide more detailed information in certificate events

---

.github/workflows/ci.yml

Following the footsteps of caddyserver/caddy#4811

Improve Windows CI cache

---

solvers.go

Simple PR about OverrideDomain setting in DNS01Solver.
The Cleanup function isn't aware of the override so the txt record is never removed (as far I see)

Use OverrideDomain when cleaning up DNS solver

---

cache.go
certificates.go
config.go
crypto.go
handshake.go
maintain.go
ocsp.go

Here is a PR to fix #197. I ended up going with a function instead of a method on `Certificate` because there are a couple places where the `NotAfter` of a `x509.Certificate` are being used. I also had a hard time figuring out how to write a test for this. It looked like the filesystem storage cache needs to be populated with a certificate and ocsp response, but i didn't see a straightforward way or any prior examples of this in other tests. Let me know if you have any thoughts on how to test this.

Add one second (at most) to account for NotAfter imprecision

---

config.go

Requesting a certificate failed, and then additionally caused rate limiting issues as well.
Certmagic version: 0.17.1
This merges #204 to a similar place in config.go.
---
Stack we have seen:
```
  | 2022-09-23T10:46:17.120Z | {"level":"error","time":"2022-09-23T10:46:17Z","module":"cert.renew","caller":"certmagic/config.go:810","msg":"could not get certificate from issuer","identifier":"XXX","issuer":"acme-v02.api.letsencrypt.org-directory","error":"HTTP 429 urn:ietf:params:acme:error:rateLimited - Error creating new order :: too many failed authorizations recently: see https://letsencrypt.org/docs/failed-validation-limit/","stacktrace":"github.com/caddyserver/certmagic.(*Config).renewCert.func2\n\t/src/vendor/github.com/caddyserver/certmagic/config.go:810\ngithub.com/caddyserver/certmagi …
```

Avoid nil dereferencing on errors

---

handshake.go

In v0.17.1, we're seeing the following panic occur (and subsequently, no recovery) over at [sish](https://github.com/antoniomika/sish). 
This occurs because we don't use zap for logging, which leads to `loggerNamed` returning `nil`. I went through and checked all other logger references and made sure they are guarded by the same issue by checking that `log` is not `nil`.
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xa1f3ca]
goroutine 537 [running]:
go.uber.org/zap.(*Logger).check(0x0, 0x2, {0xc8e025, 0x22})
/go/pkg/mod/go.uber.org/zap@v1.23.0/logger.go:291 +0x6a
go.uber.org/zap.(*Logger).Error(0xc0000ee038?, {0xc8e025?, 0x4?}, {0xc00071d300, 0x1, 0x1}) …
```

Fix a panic when attempting to log when certificate should not be renewed

---

handshake.go

This is a proposed fix for the issue reported in https://github.com/caddyserver/certmagic/issues/220.
Instead of always renewing the certificate, we first check if the corresponding resources still exist in the storage and if not use the "obtain" instead of the "renew" flow.

obtain instead of renew cert if it does not exist in storage

---

dnsutil.go

I am using the DNS challenge with the cloudflare plugin. It fails to get a certificate and results in a DNS propagation timeout error: https://github.com/caddyserver/certmagic/blob/6b92945f9db40001ef2a90a1b2c6c234e9ebddd3/solvers.go#L384
1. The cloudflare plugin successfully adds the correct TXT DNS records.
2. Running `dig -t TXT  _acme-challenge.sub.domain.com @1.1.1.1` on the caddy host machine correctly shows the TXT record very soon after the cloudflare dashboard shows the records. (So well before the default 2 minute propagation timeout)
3. Running `tcpdump port 53 and host 1.1.1.1` shows DNS queries happening every 2 seconds from caddy to 1.1.1.1. 1.1.1.1 correctly replies with the TXT records.
4. caddy appears to completely ignore the provided TXT records and eventually times out. …

Use recursive query when checking for TXT records

---

.github/workflows/ci.yml

Hi, this CI updates the CI workflow file.
This PR:
- Updates `checkout` v2 -> v3
- Updates `setup-go` v2 -> v4
- Configures `setup-go` to use the go version consistent with project setup via `go.mod` file
- Delegates build caching to `setup-go`
- Changes dependency installation to `go mod download` ([official documentation](https://go.dev/ref/mod#go-mod-download), [difference with the current `go get`](https://stackoverflow.com/questions/66356034/what-is-the-difference-between-go-get-command-and-go-mod-download-command))
- Replaces the deprecated `set-output`
- Uploads coverage file as an artifact, as currently the generated file is discarded

Update & Improve CI

---

handshake.go

This basically would allow us to pass a context into the "certmagic world", from which it then would get passed through back to our storage implementation.
The reason we want that is so that we can actually set up application performance monitoring by instrumenting the calls.
Note that this does add a new public function, but unless you specifically set your `GetCertificate` in the TLSConfig to something that uses this function, everything should stay the same.
Our setup looks like this, very simplified:
```golang
certmagicConfig.Issuers = []certmagic.Issuer{acmeIssuer}
tlsConfig := certmagicConfig.TLSConfig()
tlsConfig.GetCertificate = func(clientHelloInfo *tls.ClientHelloInfo) (*tls.Certificate, error) {
txn := monitoring.StartTransaction("TLS/GetCertificate")
defer txn.End() …
```

Add a `GetCertificateWithContext` function

---

certificates.go
certmagic.go
config.go
handshake.go

Managers necessarily have to be used during a TLS handshake, and thus can only be used in an on-demand context because we can't know whether the Manager will yield a cert until the handshake.
This commit moves the Manager configuration into OnDemandConfig, where it really belongs, which allows us to fix a few bugs, for example https://github.com/caddyserver/caddy/issues/5415.

Refactor certificate Managers

---

README.md
cache.go

Hi!
When initializing a `Cache` with `NewCache` it's easy to miss that a cache must be attached to the configuration in `CacheOptions.GetConfigForCert` and is not set by the cache itself.
If a `Config` with `certCache == nil` is used, it will cause panics at runtime (not immediately, so it's not so easy to detect the cause of the panics).
I think the proposed change to the README will address this issue and hopefully prevent other users from encountering the same problems I did, as they where not trivial to debug.
I think a good follow up discussion and possibly PR would be to look into either:
- Returning an error if `certCache == nil`, so that the error can be more easily traced to its origin.
- Filling in the `certCache` field if it's `nil`, so that the error is not possible to begin …

Fix advanced cache initialization in README

---

README.md
config.go

This implements part of #214.
Now, private keys will be generated for all new certificates instead of reused if they already exist. This behavior can be switched off by setting `ReusePrivateKeys` to `true`, but that is not recommended these days.
(Also fix some docs in the readme)

Generate new private keys for new certificates

---

README.md
certmagic.go
config.go

By default, the first issuer that returns a certificate will be used. (This is unchanged.)
If UseFirstRandomIssuer is configured, then the list of issuers will be shuffled each time before using the first one that returns a certificate.
This implementation is experimental and may change later. It's for partial completion of #214.

Issuer policies that can randomize issuer used

---

handshake.go

The context available to `renewDynamicCertificate` comes from inside the TLS handshake, and as such may be bounded by the lifespan of the connection. Passing this into a goroutine will lead to problems when the connection ends (and the connection context gets canceled with it) but the goroutine is going to do more I/O on that context.

Create a new context when renewing a certificate in the background

---

handshake.go

See discussion in #247
/cc @ankon -- I haven't tested this myself yet (been a very, very busy day with notifications rolling in all day!) but I feel like this makes the most sense. Could you try it when you have a chance?
Thanks for your patience!

Use context from ClientHello during GetCertificate

---

README.md

This hint is already present a couple of lines later, however I overlooked it in the large advanced usescase.
In my usecase I just want to customize the storage:
```go
// SETUP TLS
certmagic.DefaultACME.Email = "redacted@example.org"
certmagic.DefaultACME.Agreed = true
certmagic.DefaultACME.DisableHTTPChallenge = true
// bugfix will come here
certConfig := certmagic.NewDefault()
certConfig.Storage = &certmagic.FileStorage{
Path: stateDir + ".certmagic",
}
tlsConfig := certConfig.TLSConfig()
tlsConfig.NextProtos = append([]string{"h2", "http/1.1"}, tlsConfig.NextProtos...)
ln, err = tls.Listen("tcp", addr, tlsConfig)
if err != nil {
return err
}
if err := certConfig.ManageAsync(ctx, domains); err != nil { // async to prevent systemd restart
return fmt.Errorf("could not manage TLS …
```

README: Add hint about NextProtos for certmagic.TLS

---

certmagic.go
handshake.go

For further instrumenting our code base we would like to be able to pass the context we have when getting a certificate down into the "decision func" that checks whether a certificate should be obtained.
This PR is a bit of a "let's talk": I think this could just work, and wouldn't produce problems for existing code that only configures a `DecisionFunc`, but it can possibly be done nicer?

Optionally pass the context argument down to the OnDemand decision func

---

handshake.go

This allows an outside caller of `GetCertificate` to use `errors.As` to check for their own response and react accordingly.
In our case: The ondemand decision func checks a blocklist and might return something like `BlockedDomainError{message:"This is blocked"}`. This isn't an "error", it's just something that so happens to look like an error because that's what the decision func wants us to return.
In the GetCertificate implementation we call certmagic, and check the error it returns. If the error is "expected", then we don't really care about it and might just count it. If it is something interesting, we might want to tell a human about it.
The way that works is by having the `GetCertificate` function in a NewRelic "Transaction", and when we receive an error from certmagic we check …

Retain the error stack if `checkIfCertShouldBeObtained` returns an error

---

ocsp_test.go

I thought it might be nice to add a few more unit tests for ocsp.go. (This has been at the back of my mind since #245, and I was curious to learn a little bit more about how OCSP works.) Please let me know if you have any concerns, either on the high-level approach or on specific details.
These test cases exercise some more of the logic starting from the `stapleOCSP()` method, using a few more test certificates and an `httptest.Server` acting as the OCSP responder.
These tests are very simplistic:
- a "good" OCSP response should be stapled
- a "revoked" OCSP response should not be stapled
- the `DisableStapling` option should be honored
- OCSP stapling requires an issuing certificate
I haven't made any attempt to provide sensible timestamps, either in the test certificates or in the OCSP …

Add OCSP stapling unit tests

---

maintain.go

This isn't an actionable problem, so it doesn't make sense as a WARN.
It shows up in startup logs pretty often if starting and stopping Caddy, slightly annoying.

Demote "storage cleaning happened too recently" from WARN to INFO

---

dnsutil.go
solvers.go

Discussion in https://github.com/caddyserver/certmagic/issues/219

Check DNS propagation at authoritative nameservers only with default resolvers

---

account.go
acmeissuer.go

If the CA server got reinstalled or reset, retry with new account credentials.
Obviously this would be a disaster for a public CA, but it's possible that internal PKI gets reset and our client should gracefully try again.
It's a good opportunity to rotate the private key and I also found deleting the old key/reg info to be the easiest way to get CertMagic to try again with new credentials.

Retry with new account if account disappeared remotely

---

README.md

There's a couple of references to `tlsalpn01.ACMETLS1Protocol` in the readme. I've changed them to `acmez.ACMETLS1Protocol`.
I think these should have been changed when CertMagic switched from lego to ACMEz: https://github.com/caddyserver/certmagic/commit/b76b76abfcacf44350226e59907fbdc23b31f489

Update readme examples to use TLS-ALPN const from ACMEz

---

account.go
account_test.go

When the issuer is configured with both an email and key material, these should match -- but that also means we can use the email information to predict the key-key, skipping the potentially expensive storage.List operation.

Use the `email` configuration in the ACME issuer to "pin" an account to a key

---

acmeclient.go
acmeissuer.go
certificates.go
certmagic.go
config.go
config_test.go
go.mod
go.sum
handshake.go
maintain.go
zerosslissuer.go

Add ARI (ACME Renewal Information) support.
ARI is currently in draft spec and subject to change: https://datatracker.ietf.org/doc/draft-ietf-acme-ari/03/
For certificates issued with ACME, if the ACME server supports it, CertMagic now considers ARI to trigger renewals.
As usual, the maintenance timer keeps certificates renewed, but now we also refresh ARI if it is time to poll again, and we also use ARI as a determining factor for triggering renewal in addition to the expiration date / lifetime. By default, maintenance routines run every 10 minutes so we will likely not miss an ARI change.
We also store ARI along with the certificate and its other metadata. This means that multiple Caddy instances can share the same ARI data. While we don't strictly synchronize the updating of ARI, it is …

Initial implementation of ARI

---

handshake.go

Currently, we only use `DefaultServerName` for choosing a certificate. This doesn't make a lot of sense, because if that is set to a name that doesn't have a cert managed for it, it will not be of much use because we'd use the IP address to fill in an empty ServerName when doing logic, but only using DefaultServerName when loading the certs. So things didn't line up sometimes.
This change makes it so that DefaultServerName will always be used as the ServerName when it was empty, meaning that the IP address will never be used as the "name". This is more expected behavior. (So obviously, if you WANT to serve your IP address over TLS, then don't set DefaultServerName.)
This is being deployed soon to a production environment but is so far working well in staging. Likely to be merged into …

Apply DefaultServerName more broadly during handshake

---

go.mod
go.sum

This currently does not work because it requires caddyserver/zerossl#1 to be merged first. That dependency forced this module to upgrade its minimum Go version. That is not needed, and it's causing pains due to mis-synchronization with other parts of Caddy ecosystem. Once caddyserver/zerossl#1 is merged, the dependency here can be updated to use the next patch release of the zerossl package, then do `go mod tidy` and set this PR to be ready.
Depends on caddyserver/zerossl#1

downgrade minimum Go version

---

account.go
acmeclient.go

This implements a distributed lock around registering new ACME accounts. I am not sure why this issue hasn't really appeared before, whether a recent change exposed this bug that we've always had, or we recently introduced this bug:
https://caddy.community/t/lets-encrypt-hits-rate-limit-too-many-registrations-for-this-ip/24343
Hoping this will tame things a bit. Makes sense in my head.

Sync ACME account registration

---

filestorage.go
filestorage_test.go
internal/atomicfile/README
internal/atomicfile/file.go
internal/atomicfile/file_test.go
internal/testutil/readme.md
internal/testutil/testutil.go

discovered in #296 
there is a currently a race between file deletion and rewrite which can cause an empty read. 
copying the method used by containerd, https://github.com/containerd/containerd/blob/main/pkg%2Fatomicfile%2Ffile.go the problem can be solved via a flushing a temporary file

fix: use a tempfile to write files in filestorage. 

---

certificates.go
certificates_test.go

ICANN is in the progress of reserving `.internal` for private use (see [this closed consultation](https://www.icann.org/en/public-comment/proceeding/proposed-top-level-domain-string-for-private-use-24-01-2024)). As such I believe that this TLD would be a suitable addition to the list of internal addresses used in `SubjectIsInternal`.
I based this PR on 6668587 which added `.home.arpa` to the list.

Add .internal to internal-only hostnames

---

README.md

All of dotGo's videos have been transferred to YouTube.

Repair broken link for dotGo presentation.

---

zerosslissuer.go

This PR adds the `PollInterval` option to the `ZeroSSLIssuer`, which lets users adjust the polling interval for certificate retrieval when using the ZeroSSL issuer.
If no `PollInterval` is configured (or a value of `0` is set), the default poll interval of 5 seconds is used.

ZeroSSLIssuer: Make PollInterval configurable

---

zerosslissuer.go

The validation path prefix is likely now `zerosslHTTPValidationBasePath`, and the API base here is broken (`"https://" + somethingThatIncludesHTTPSAsWell`).

Remove obsolete constants

---

handshake.go

In cases where we only have a single certificate to choose from we will anyways pick that certificate, regardless of whether the certificate is supported by the client or is expired.

Add a fast path for the DefaultCertificateSelector

---

certificates.go
handshake.go
ocsp.go

In Caddy, we often get warnings like these when using internally issued certs:
```
{"level":"warn","ts":1731027618.3063543,"logger":"tls","msg":"stapling OCSP","error":"no OCSP stapling for [localhost]: no OCSP server specified in certificate","identifiers":["localhost"]}
```
These generally have a very short lifetime and for that reason warning about them not having OCSP configured is just noise, because OCSP on short certs isn't too useful.
I added a `Lifetime()` method to help here, I used `expiresAt` for the "1s resolution of ASN.1 UTCTime/GeneralizedTime", hope that's correct.

Quiet OCSP warnings if the cert has a short lifetime

---

account_test.go
internal/testutil/testutil.go

This PR replaces a few occurrences of `interface{}` with newer `any` syntax.

Replace interface{} with any

---

handshake.go
maintain.go

Using a context that expires after the handshake cancels, for a background task, is no good!
Also avoid unnecessary ARI maintenance, if cert is expired, it'll try to be renewed regardless.

ari: Only check if cert is not expired, and use proper context

---

acmeissuer.go

See: https://letsencrypt.org/2025/07/01/issuing-our-first-ip-address-certificate/

acmeissuer: LE now supports IP certs

---

cache.go
maintain.go

getConfig checks cfg.certCache so cfg can never be nil inside of getConfig or it can crash with:
invalid memory address or nil pointer dereference

Move cfg nil check from RenewManagedCertificates to getConfig
